### ISSUE TITLE
IMX585 driver

### ISSUE THREAD

**Issue by petergerten** [will127534/StarlightEye#2]
That's a very interesting project!
I can't find the IMX585 driver - any hints?

**Comment by will127534** [comment]
I do have the driver but I'm in the progress of updating it for RPI5, here is the V4l2subdevice driver sketch:
[https://gist.github.com/will127534/f734a32b18b44d57448b4e46d07bb1c7](https://gist.github.com/will127534/f734a32b18b44d57448b4e46d07bb1c7)

Will release once I sort out the issue.

**Comment by petergerten** [comment]
@will127534 thanks!

In general can you tell me how much board specific this driver is?
E.g. to port it to a non-pi board with MIPI/CSI interface

**Comment by will127534** [comment]
This is very specific for RPI, which non-pi board are you looking into?
If you know how to write camera driver for other platform I think it is actually not that bad because the driver only implements one mode and it is setup with the init-register array, so you just need to send those and setup the CSI receiver accordingly.

**Comment by petergerten** [comment]
sorry for the late reply, I missed this message.

I am looking for integration with Qualcomm RB5 (https://www.qualcomm.com/developer/robotics-rb5-development-kit)

**Comment by will127534** [comment]
[https://github.com/will127534/imx585-v4l2-driver/tree/main](https://github.com/will127534/imx585-v4l2-driver/tree/main)
